spring:
  jpa:
    database-platform: "com.example.bot.model.SQLDialect"
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:sqlite:x-ui.db"
    driver-class-name: org.sqlite.JDBC
    username: "admin"
    password: "admin"
khoinda:
  bot:
    username: "thunder_reportBot"
    token: "5604897269:AAH2igtZlOjUGMX3q72ojXDsAx8pc2_IcwQ"
    bot-route-packages:
      - "com.example.bot"
    enable-auto-config: true