spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: com.example.bot.model.SQLDialect
    generate-ddl: true
    show-sql: true
    database-platform: com.example.bot.model.SQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:sqlite:src/main/resources/db/x-ui.db
    driver-class-name: org.sqlite.JDBC