spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: com.example.bot.model.SQLDialect
    generate-ddl: true
    show-sql: true
    database-platform: com.example.bot.model.SQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:x-ui.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

#khoinda:
#  bot:
#    username: thunder_reportBot
#    token: 5604897269:AAH2igtZlOjUGMX3q72ojXDsAx8pc2_IcwQ
#    bot-route-packages:
#      - com.example.bot
#    enable-auto-config: true
#    bot-owner-chat-id:
#      - 5724979708
#    logging-chat-id: 1577189814
#    disable-default-commands: true